### ISSUE TITLE
Error in plugin gulp

### ISSUE THREAD

**Issue by hdrk2k** [app-generator/django-volt-dashboard-pro2#1]
I receive the following error when I try to compile sass.

[14:04:36] Starting 'sass'...
[14:04:36] 'sass' errored after 245 ms
[14:04:36] Error in plugin "gulp-sass"
Message:
    ../../node_modules/bootstrap/scss/_functions.scss
Error: argument `$color` of `rgba($color, $alpha)` must be a color
        on line 150 of ../../node_modules/bootstrap/scss/_functions.scss, in function `rgba`
        from line 150 of ../../node_modules/bootstrap/scss/_functions.scss, in function `opaque`
        from line 4 of ../../node_modules/bootstrap/scss/mixins/_table-variants.scss, in mixin `table-variant`
        from line 134 of ../../node_modules/bootstrap/scss/_tables.scss
        from line 22 of ../../node_modules/bootstrap/scss/bootstrap.scss
        from line 28 of core/static/assets/scss/volt.scss
>>   @return mix(rgba($foreground, 1), $background, opacity($foreground) * 100)
   --------------^
Mac OS: 10.15.7
gulp-sass: 4.1.0

gulpfile.js

```
var gulp        = require('gulp');
var browserSync = require('browser-sync').create();
var sass        = require('gulp-sass');

// Compile sass into CSS & auto-inject into browsers
gulp.task('sass', function() {
    return gulp.src("core/static/assets/scss/volt.scss")
        .pipe(sass())
        .pipe(gulp.dest("test/css"))
        .pipe(browserSync.stream());
});

// Static Server + watching scss/html files
gulp.task('serve', gulp.series('sass', function() {

    browserSync.init({
        server: "./test/"
    });

    gulp.watch("core/static/assets/scss/volt.scss", gulp.series('sass'));
    gulp.watch("test/*.html").on('change', browserSync.reload);
}));

gulp.task('default', gulp.series('serve'));
```

**Comment by hdrk2k** [comment]
I tried using sass from the cli and it still comes back with the same error so I don't think it's a gulp problem.
sass core/static/assets/scss/volt.scss test/main.css
### sass version 1.29.0 

### error message
Error: $color: color-level(#262B40, -9) is not a color.
    ╷
150 │   @return mix(rgba($foreground, 1), $background, opacity($foreground) * 100);
    │               ^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/bootstrap/scss/_functions.scss 150:15            opaque()
  node_modules/bootstrap/scss/mixins/_table-variants.scss 4:28  table-variant()
  node_modules/bootstrap/scss/_tables.scss 133:3                @import
  node_modules/bootstrap/scss/bootstrap.scss 22:9               @import
  core/static/assets/scss/volt.scss 28:9                        root stylesheet

### sass command

`sass core/static/assets/scss/volt.scss test/main.css`

**Comment by app-generator** [comment]
The starter is not provided with SCSS compilation support via gulp or any other builder (aka Webpack).
For such a thing, we can provide the HTML version that comes with a usable toolchain.  

We noted this case and the documentation will be updated to explain the process.
