### ISSUE TITLE
Unable to compile the minified version of the HTML and CSS from Volt Pro

### ISSUE THREAD

**Issue by DenPaz** [app-generator/django-volt-dashboard-pro2#5]
I'm following the README.md guide but I've got the following error during the process:

![image](https://user-images.githubusercontent.com/97189999/167261352-8d8e850a-ca35-4055-b2ba-7c95a9cc8011.png)

What should I do?

**Comment by app-generator** [comment]
Tested ok with Gulp 4 and Node 12.x.
Closing.
